-- Schema para tablas de ejemplo
CREATE TABLE leccionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asignatura VARCHAR(255) NOT NULL,
  fecha DATE,
  contenido VARCHAR(2000),
  id_profesor BIGINT
);
