-- Schema para tablas de ejemplo
CREATE TABLE cursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE  leccionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asignatura VARCHAR(255) NOT NULL,
  fecha DATE,
  contenido VARCHAR(2000),
  id_profesor BIGINT,
  id_curso BIGINT,
  CONSTRAINT fk_curso FOREIGN KEY (id_curso) REFERENCES cursos(id)
);
