spring:
    application:
        name: hojadevida
    datasource:
        url: jdbc:mysql://localhost:3306/hojadevida
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
    flyway:
        enabled: true
        locations: classpath:db/migration

server:
    port: 9005

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
    
logging:   
    level:
        root: INFO
        com.proyecto.hojadevida: DEBUG
    file:
        name: logs/hojadevida-service.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui/index.html